### ISSUE TITLE
Error when the propType isn't specified

### ISSUE THREAD

**Issue by daryl** [segmentio/deku#92] opened 2015-05-09 23:58 UTC
When using the `set` function, if the propType isn't specified this error occurs.

```
Uncaught TypeError: connections[name] is not a function
```

```js
const App = {
  propTypes: {
    foo: {
      source: 'foo'
    }
  },

  render(comp) {
    let {props} = comp;
    let {foo} = props;

    return (
      <div>
        {foo || 'App'}
      </div>
    );
  }
}

const app = tree(<App/>);

render(app, document.body);

app.set('foo', 'bar');
```

[Demo](http://requirebin.com/?gist=ef6bfb49421922bbe602).

**Comment by anthonyshort** [comment] 2015-05-10 02:44
Yeah this is a dupe of #81 I think. If it's set before the initial render it should be fine.

**Closed** 2015-05-12 19:44 UTC
